development:
  adapter: postgresql
  host: localhost
  username: user
  database: app-dev
  pool: 5
  username: wellis
  password: NinjaDopingIgnoramusGestapo

test:
  adapter: postgresql
  host: localhost
  username: user
  database: app-test
  pool: 5
  username: wellis
  password: NinjaDopingIgnoramusGestapo

production:
  adapter: postgresql 
  host: localhost 
  username: user 
  database: app-prod
  pool: 5
  username: wellis
  password: NinjaDopingIgnoramusGestapo 

