development:
  adapter: postgresql
  host: localhost
  database: app-dev
  pool: 5
  username: unprivdbuser
  password: pianounicyclecardboardgymnasium

test:
  adapter: postgresql
  host: localhost
  database: app-test
  pool: 5
  username: unprivdbuser
  password: pianounicyclecardboardgymnasium

production:
  adapter: postgresql 
  host: localhost 
  database: app-prod
  pool: 5
  username: unprivdbuser
  password: pianounicyclecardboardgymnasium

